{% set version = "0.0.59" %}

package:
  name: langchain-experimental
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/langchain-experimental/langchain_experimental-{{ version }}.tar.gz
  sha256: 3a93f5c328f6ee1cd4f9dd8792c535df2d5638cff0d778ee25546804b5282fda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - langchain >=0.1.15,<0.2.0
    - langchain-core >=0.1.41,<0.2.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_experimental

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/experimental
  license: MIT
  license_file: LICENSE
  summary: This package holds experimental LangChain code, intended for research and experimental uses.

extra:
  recipe-maintainers:
    - raybellwaves
