{% set version = "0.0.65" %}

package:
  name: langchain-experimental
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/langchain-experimental/langchain_experimental-{{ version }}.tar.gz
  sha256: 83706df07d8a7e6ec1bda74174add7e4431b5f4a8818e19b65986b94c9c99b25

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.7,<0.3.0
    - langchain-community <0.3.0,>=0.2.16

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_experimental

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/experimental
  license: MIT
  license_file: LICENSE
  summary: This package holds experimental LangChain code, intended for research and experimental uses.

extra:
  recipe-maintainers:
    - raybellwaves
    - jan-janssen
