{% set version = "0.3.4" %}

package:
  name: langchain-experimental
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-experimental/langchain_experimental-{{ version }}.tar.gz
  sha256: 937c4259ee4a639c618d19acf0e2c5c2898ef127050346edc5655259aa281a21

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core <0.4.0,>=0.3.0
    - langchain-community <0.4.0,>=0.3.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_experimental

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/experimental
  license: MIT
  license_file: LICENSE
  summary: This package holds experimental LangChain code, intended for research and experimental uses.

extra:
  recipe-maintainers:
    - raybellwaves
    - jan-janssen
